
-- PL_1//Scope 2/1. UK electricity.csv
INSERT INTO "Scope 2" ("id", "Scope", "Level 1", "Level 2", "Level 3", "Level 4", "UOM", "GHG/Unit", "GHG Conversion Factor")
 VALUES ('index', 'Scope', 'Level 1', 'Activity', 'Country', 'Last level', 'UOM', 'GHG/Unit', 'GHG Conversion Factor')
, ('2110', 'Scope 2', 'UK electricity', 'Electricity generated', 'Electricity: UK', 'kWh', 'kWh', 'kg CO2e', '0.177')
, ('2110', 'Scope 2', 'UK electricity', 'Electricity generated', 'Electricity: UK', 'kWh', 'kWh', 'kg CO2e of CO2 per unit', '0.17489')
, ('2110', 'Scope 2', 'UK electricity', 'Electricity generated', 'Electricity: UK', 'kWh', 'kWh', 'kg CO2e of CH4 per unit', '0.0009')
, ('2110', 'Scope 2', 'UK electricity', 'Electricity generated', 'Electricity: UK', 'kWh', 'kWh', 'kg CO2e of N2O per unit', '0.00122');
-- PL_1//Scope 2/2. UK electricity for EVs.csv
INSERT INTO "Scope 2" ("id", "Scope", "Level 1", "Level 2", "Level 3", "Level 4", "UOM", "GHG/Unit", "GHG Conversion Factor")
 VALUES ('index', 'Scope', 'Level 1', 'Activity', 'Type', 'Last level', 'UOM', 'GHG/Unit', 'GHG Conversion Factor')
, ('2310', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', NULL)
, ('2311', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', NULL)
, ('2312', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.02408')
, ('2313', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.03877')
, ('2314', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.009')
, ('2315', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.01448')
, ('2316', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.00964')
, ('2317', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.01553')
, ('2318', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.00793')
, ('2319', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.01274')
, ('23110', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.00924')
, ('23111', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.01488')
, ('23112', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.00675')
, ('23113', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.01085')
, ('23114', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.01319')
, ('23115', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.02124')
, ('23116', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.01674')
, ('23117', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.02695')
, ('2310', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', NULL)
, ('2311', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', NULL)
, ('2312', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.02378')
, ('2313', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.03828')
, ('2314', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.00881')
, ('2315', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.01417')
, ('2316', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.00945')
, ('2317', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.01521')
, ('2318', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.00772')
, ('2319', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.01242')
, ('23110', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.00902')
, ('23111', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.01452')
, ('23112', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.00658')
, ('23113', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.01059')
, ('23114', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.01292')
, ('23115', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.02079')
, ('23116', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.01634')
, ('23117', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.0263')
, ('2310', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', NULL)
, ('2311', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', NULL)
, ('2312', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00012')
, ('2313', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.0002')
, ('2314', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '8e-05')
, ('2315', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00013')
, ('2316', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '8e-05')
, ('2317', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00013')
, ('2318', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '9e-05')
, ('2319', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00013')
, ('23110', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '9e-05')
, ('23111', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00016')
, ('23112', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '7e-05')
, ('23113', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00011')
, ('23114', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00011')
, ('23115', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00019')
, ('23116', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00017')
, ('23117', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00028')
, ('2310', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', NULL)
, ('2311', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', NULL)
, ('2312', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00018')
, ('2313', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00028')
, ('2314', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00012')
, ('2315', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00018')
, ('2316', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00012')
, ('2317', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00019')
, ('2318', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00012')
, ('2319', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00019')
, ('23110', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00013')
, ('23111', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.0002')
, ('23112', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.0001')
, ('23113', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00015')
, ('23114', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00016')
, ('23115', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00026')
, ('23116', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00023')
, ('23117', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00037')
, ('2310', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03005')
, ('2311', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.04836')
, ('2312', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03419')
, ('2313', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.05502')
, ('2314', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03483')
, ('2315', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.05606')
, ('2316', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03781')
, ('2317', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.06086')
, ('2318', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03351')
, ('2319', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.05392')
, ('23110', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.04438')
, ('23111', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.07141')
, ('23112', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.05667')
, ('23113', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.0912')
, ('23114', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03826')
, ('23115', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.0616')
, ('23116', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.04709')
, ('23117', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.07578')
, ('2310', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.02965')
, ('2311', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.04772')
, ('2312', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03377')
, ('2313', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.05434')
, ('2314', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03435')
, ('2315', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.05529')
, ('2316', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03746')
, ('2317', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.06028')
, ('2318', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03304')
, ('2319', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.05317')
, ('23110', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.04383')
, ('23111', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.07053')
, ('23112', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.05599')
, ('23113', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.09011')
, ('23114', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03765')
, ('23115', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.0606')
, ('23116', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.04646')
, ('23117', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.07477')
, ('2310', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00017')
, ('2311', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00027')
, ('2312', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00018')
, ('2313', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00029')
, ('2314', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.0002')
, ('2315', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00032')
, ('2316', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00015')
, ('2317', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00025')
, ('2318', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.0002')
, ('2319', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00031')
, ('23110', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00024')
, ('23111', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00037')
, ('23112', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00029')
, ('23113', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00046')
, ('23114', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00026')
, ('23115', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00043')
, ('23116', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00027')
, ('23117', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00043')
, ('2310', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00023')
, ('2311', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00037')
, ('2312', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00024')
, ('2313', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00039')
, ('2314', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00028')
, ('2315', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00044')
, ('2316', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.0002')
, ('2317', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00033')
, ('2318', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00027')
, ('2319', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00044')
, ('23110', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00031')
, ('23111', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00051')
, ('23112', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00039')
, ('23113', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00063')
, ('23114', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00036')
, ('23115', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00058')
, ('23116', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00036')
, ('23117', 'Scope 2', 'UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00059')
, ('2320', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.02408')
, ('2321', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.03877')
, ('2322', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.00931')
, ('2323', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.01499')
, ('2324', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.01266')
, ('2325', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.02037')
, ('2326', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.01171')
, ('2327', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.01885')
, ('2320', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.02378')
, ('2321', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.03828')
, ('2322', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.00912')
, ('2323', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.01468')
, ('2324', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.0124')
, ('2325', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.01995')
, ('2326', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.01148')
, ('2327', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.01847')
, ('2320', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00012')
, ('2321', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.0002')
, ('2322', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '8e-05')
, ('2323', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00013')
, ('2324', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00011')
, ('2325', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00018')
, ('2326', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.0001')
, ('2327', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00016')
, ('2320', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00018')
, ('2321', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00028')
, ('2322', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00012')
, ('2323', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00018')
, ('2324', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00015')
, ('2325', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00024')
, ('2326', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00013')
, ('2327', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00022')
, ('2320', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03339')
, ('2321', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.05372')
, ('2322', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03513')
, ('2323', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.05654')
, ('2324', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03807')
, ('2325', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.06127')
, ('2326', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03663')
, ('2327', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.05894')
, ('2320', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03297')
, ('2321', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.05306')
, ('2322', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03465')
, ('2323', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.05577')
, ('2324', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03751')
, ('2325', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.06037')
, ('2326', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03613')
, ('2327', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.05814')
, ('2320', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00018')
, ('2321', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00028')
, ('2322', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.0002')
, ('2323', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00032')
, ('2324', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00024')
, ('2325', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00038')
, ('2326', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00021')
, ('2327', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00034')
, ('2320', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00024')
, ('2321', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00038')
, ('2322', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00028')
, ('2323', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00044')
, ('2324', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00032')
, ('2325', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00052')
, ('2326', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00028')
, ('2327', 'Scope 2', 'UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00046')
, ('2330', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e', NULL)
, ('2331', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', NULL)
, ('2332', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', NULL)
, ('2333', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e', NULL)
, ('2334', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', NULL)
, ('2335', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', NULL)
, ('2336', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e', '0.03527')
, ('2337', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.01392')
, ('2338', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.0224')
, ('2339', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e', '0.03527')
, ('23310', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e', '0.01392')
, ('23311', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e', '0.0224')
, ('2330', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of CO2 per unit', NULL)
, ('2331', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', NULL)
, ('2332', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', NULL)
, ('2333', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of CO2 per unit', NULL)
, ('2334', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', NULL)
, ('2335', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', NULL)
, ('2336', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of CO2 per unit', '0.03487')
, ('2337', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.01376')
, ('2338', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.02214')
, ('2339', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of CO2 per unit', '0.03487')
, ('23310', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.01376')
, ('23311', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.02214')
, ('2330', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of CH4 per unit', NULL)
, ('2331', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', NULL)
, ('2332', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', NULL)
, ('2333', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of CH4 per unit', NULL)
, ('2334', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', NULL)
, ('2335', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', NULL)
, ('2336', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of CH4 per unit', '0.00017')
, ('2337', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '7e-05')
, ('2338', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00011')
, ('2339', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of CH4 per unit', '0.00017')
, ('23310', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '7e-05')
, ('23311', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00011')
, ('2330', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of N2O per unit', NULL)
, ('2331', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', NULL)
, ('2332', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', NULL)
, ('2333', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of N2O per unit', NULL)
, ('2334', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', NULL)
, ('2335', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', NULL)
, ('2336', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of N2O per unit', '0.00023')
, ('2337', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '9e-05')
, ('2338', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00015')
, ('2339', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kg CO2e of N2O per unit', '0.00023')
, ('23310', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '9e-05')
, ('23311', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00015')
, ('2330', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e', '0.11293')
, ('2331', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.03438')
, ('2332', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.05534')
, ('2333', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e', '0.22553')
, ('2334', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.05229')
, ('2335', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.08415')
, ('2336', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e', '0.18574')
, ('2337', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.06887')
, ('2338', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.11085')
, ('2339', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e', '0.19907')
, ('23310', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e', '0.06315')
, ('23311', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e', '0.10162')
, ('2330', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of CO2 per unit', '0.11121')
, ('2331', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.03402')
, ('2332', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.05476')
, ('2333', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of CO2 per unit', '0.22329')
, ('2334', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.05179')
, ('2335', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.08335')
, ('2336', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of CO2 per unit', '0.18365')
, ('2337', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.06818')
, ('2338', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.10973')
, ('2339', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of CO2 per unit', '0.19684')
, ('23310', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of CO2 per unit', '0.06265')
, ('23311', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CO2 per unit', '0.10082')
, ('2330', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of CH4 per unit', '0.00073')
, ('2331', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00016')
, ('2332', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00025')
, ('2333', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of CH4 per unit', '0.00095')
, ('2334', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00021')
, ('2335', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00034')
, ('2336', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of CH4 per unit', '0.00088')
, ('2337', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00029')
, ('2338', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00047')
, ('2339', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of CH4 per unit', '0.00094')
, ('23310', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of CH4 per unit', '0.00021')
, ('23311', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of CH4 per unit', '0.00034')
, ('2330', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of N2O per unit', '0.00099')
, ('2331', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.0002')
, ('2332', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00034')
, ('2333', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of N2O per unit', '0.00129')
, ('2334', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00028')
, ('2335', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00046')
, ('2336', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of N2O per unit', '0.00121')
, ('2337', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.0004')
, ('2338', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00065')
, ('2339', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kg CO2e of N2O per unit', '0.00129')
, ('23310', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kg CO2e of N2O per unit', '0.00028')
, ('23311', 'Scope 2', 'UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kg CO2e of N2O per unit', '0.00046');
-- PL_1//Scope 2/3. SECR kWh UK electricity for EVs.csv
INSERT INTO "Scope 2" ("id", "Scope", "Level 1", "Level 2", "Level 3", "Level 4", "UOM", "GHG/Unit", "GHG Conversion Factor")
 VALUES ('index', 'Scope', 'Level 1', 'Activity', 'Type', 'Last level', 'UOM', 'GHG/Unit', 'GHG Conversion Factor')
, ('2410', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', NULL)
, ('2411', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', NULL)
, ('2412', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.13599')
, ('2413', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.21885')
, ('2414', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.05035')
, ('2415', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.08103')
, ('2416', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.05403')
, ('2417', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.08696')
, ('2418', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.04412')
, ('2419', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.07101')
, ('24110', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.05159')
, ('24111', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.08303')
, ('24112', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.03764')
, ('24113', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.06057')
, ('24114', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.07385')
, ('24115', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.11886')
, ('24116', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.09345')
, ('24117', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.15039')
, ('2410', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.16955')
, ('2411', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Mini', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.27286')
, ('2412', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.19308')
, ('2413', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Supermini', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.31072')
, ('2414', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.19642')
, ('2415', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Lower medium', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.31611')
, ('2416', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.21417')
, ('2417', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Upper medium', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.34468')
, ('2418', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.18891')
, ('2419', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Executive', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.30403')
, ('24110', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.2506')
, ('24111', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Luxury', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.4033')
, ('24112', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.32014')
, ('24113', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Sports', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.51521')
, ('24114', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.21529')
, ('24115', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'Dual purpose 4X4', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.34648')
, ('24116', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.26566')
, ('24117', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by market segment)', 'MPV', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.42754')
, ('2420', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.13599')
, ('2421', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Small car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.21885')
, ('2422', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.05216')
, ('2423', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.08394')
, ('2424', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.07088')
, ('2425', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Large car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.11406')
, ('2426', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.06562')
, ('2427', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Average car', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.10561')
, ('2420', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.18852')
, ('2421', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Small car', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.30339')
, ('2422', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.19814')
, ('2423', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Medium car', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.31888')
, ('2424', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.21449')
, ('2425', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Large car', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.34519')
, ('2426', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.20656')
, ('2427', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Cars (by size)', 'Average car', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.33243')
, ('2430', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kWh (net)', NULL)
, ('2431', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', NULL)
, ('2432', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', NULL)
, ('2433', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kWh (net)', NULL)
, ('2434', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', NULL)
, ('2435', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', NULL)
, ('2436', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kWh (net)', '0.19938')
, ('2437', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.07866')
, ('2438', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.12659')
, ('2439', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'tonne.km', 'kWh (net)', '0.19938')
, ('24310', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'km', 'kWh (net)', '0.07866')
, ('24311', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Plug-in Hybrid Electric Vehicle', 'miles', 'kWh (net)', '0.12659')
, ('2430', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kWh (net)', '0.6359')
, ('2431', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.19454')
, ('2432', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class I (up to 1.305 tonnes)', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.31308')
, ('2433', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kWh (net)', '1.27672')
, ('2434', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.29614')
, ('2435', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class II (1.305 to 1.74 tonnes)', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.47659')
, ('2436', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kWh (net)', '1.05006')
, ('2437', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.38984')
, ('2438', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Class III (1.74 to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.62739')
, ('2439', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'tonne.km', 'kWh (net)', '1.12547')
, ('24310', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'km', 'kWh (net)', '0.3582')
, ('24311', 'Scope 2', 'SECR kWh UK electricity for EVs', 'Vans', 'Average (up to 3.5 tonnes)', 'Battery Electric Vehicle', 'miles', 'kWh (net)', '0.57647');
-- PL_1//Scope 2/4. Heat and steam.csv
INSERT INTO "Scope 2" ("id", "Scope", "Level 1", "Level 2", "Level 3", "Level 4", "UOM", "GHG/Unit", "GHG Conversion Factor")
 VALUES ('index', 'Scope', 'Level 1', 'Activity', 'Type', 'Last level', 'UOM', 'GHG/Unit', 'GHG Conversion Factor')
, ('2510', 'Scope 2', 'Heat and steam', 'Heat and steam', 'Onsite heat and steam', 'kWh', 'kWh', 'kg CO2e', '0.17529')
, ('2511', 'Scope 2', 'Heat and steam', 'Heat and steam', 'District heat and steam', 'kWh', 'kWh', 'kg CO2e', '0.17529')
, ('2510', 'Scope 2', 'Heat and steam', 'Heat and steam', 'Onsite heat and steam', 'kWh', 'kWh', 'kg CO2e of CO2 per unit', '0.17355')
, ('2511', 'Scope 2', 'Heat and steam', 'Heat and steam', 'District heat and steam', 'kWh', 'kWh', 'kg CO2e of CO2 per unit', '0.17355')
, ('2510', 'Scope 2', 'Heat and steam', 'Heat and steam', 'Onsite heat and steam', 'kWh', 'kWh', 'kg CO2e of CH4 per unit', '0.00122')
, ('2511', 'Scope 2', 'Heat and steam', 'Heat and steam', 'District heat and steam', 'kWh', 'kWh', 'kg CO2e of CH4 per unit', '0.00122')
, ('2510', 'Scope 2', 'Heat and steam', 'Heat and steam', 'Onsite heat and steam', 'kWh', 'kWh', 'kg CO2e of N2O per unit', '0.00052')
, ('2511', 'Scope 2', 'Heat and steam', 'Heat and steam', 'District heat and steam', 'kWh', 'kWh', 'kg CO2e of N2O per unit', '0.00052');